apiVersion: batch/v1
kind: Job
metadata:
  name: ddp-worker-1
spec:
  template:
    metadata:
      labels:
        app: ddp
        role: worker
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: 127393435473.dkr.ecr.us-east-1.amazonaws.com/ddp-training:0.1
          imagePullPolicy: Always

          command: ["torchrun"]

          args:
            - "--nproc_per_node=1"
            - "--nnodes=2"
            - "--node_rank=1"

            - "--rdzv_backend=static"
            - "--rdzv_endpoint=ddp-master-svc:29500"

            - "--master_addr=ddp-master-svc"
            - "--master_port=29500"

            - "/app/src/train.py"

          env:
            - name: GLOO_SOCKET_IFNAME
              value: "eth0"