apiVersion: batch/v1
kind: Job
metadata:
  name: ddp-worker-1
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: ddp
        role: worker
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: ddp-mnist:0.1
          imagePullPolicy: Never

          command: ["torchrun"]

          args:
            - "--nproc_per_node=1"
            - "--nnodes=2"
            - "--node_rank=1"
            - "--rdzv_backend=c10d"
            - "--rdzv_endpoint=ddp-master-svc:29500"
            - "--rdzv_id=mnist-ddp"
            - "/app/src/train.py"